#!/usr/bin/env bash

set -euo pipefail

# Align EvidentialGene-curated transcriptomes against the
# Thecaphora frezzii reference genome using Subread.
#
# This script can be used for transcriptomes generated by either:
#   1. read-classification-based de novo reconstruction
#   2. genome-guided reconstruction
#
# Usage:
#   bash subread_fungal_alignment.sh \
#       <curated_transcriptome.mrna> \
#       <subread_index_prefix> \
#       <output_prefix> \
#       [threads]
#
# Example:
#   bash subread_fungal_alignment.sh \
#       Trinity_GG_Gra.okay.mrna \
#       /path/to/thecaphora_index \
#       Gra_GG_vs_Tfrezzii \
#       10

INPUT_FASTA="$1"
INDEX_PREFIX="$2"
OUTPUT_PREFIX="$3"
THREADS="${4:-10}"

if [ ! -f "$INPUT_FASTA" ]; then
    echo "Error: input transcriptome not found: $INPUT_FASTA"
    exit 1
fi

echo "Input transcriptome: $INPUT_FASTA"
echo "Subread index: $INDEX_PREFIX"
echo "Output: ${OUTPUT_PREFIX}.bam"
echo "Threads: $THREADS"
echo

subread-align \
    -i "$INDEX_PREFIX" \
    -r "$INPUT_FASTA" \
    -t 0 \
    -o "${OUTPUT_PREFIX}.bam" \
    -T "$THREADS"

echo
echo "Alignment completed: ${OUTPUT_PREFIX}.bam"
